#https://mmistakes.github.io/minimal-mistakes/docs/configuration/

title: Your awesome title 1
logo: /images/arezoo.jpg
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
theme: minima
  # generate social links in footer

 

plugins:
 - jekyll-feed
 - jekyll-seo-tag


# theme: jekyll-theme-minimal
# title:  Arezoo Rajabi
# email: your-email@domain.com
# logo: /images/arezoo.jpg



# github: 
#   is_project_page: false
