#https://mmistakes.github.io/minimal-mistakes/docs/configuration/



theme: jekyll-theme-minimal
title:  Arezoo Rajabi
email: your-email@domain.com
logo: /images/arezoo.jpg



github: 
  is_project_page: false
