#https://mmistakes.github.io/minimal-mistakes/docs/configuration/
theme: jekyll-theme-minimal
title:  Arezoo Rajabi

author: Some Person

avatar: "/images/arezoo.jpg"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

social-network-links:
  email: "someone@example.com"
  linkedin: daattali


#logo: /images/arezoo.jpg
#title:  Arezoo Rajabi
#subtitle: Graduate Research Assistant
#description: rajabia@oregonstate.edu
#minimal_mistakes_skin: "contrast" #"default", "air", "aqua", "contrast",
# author: 
  #name     : "Arezoo Rajabi"
#   avatar   : "/images/arezoo.jpg"
#   bio      : "My awesome biography constrained to a sentence or two goes here."
#   location : "Corvallis, US"
#   links:
#       - label: "Email"
#         icon: "fas fa-fw fa-envelope-square"
#         url: "rajabia@oregonstate.edu"
#       - label: "Website"
#         icon: "fas fa-fw fa-link"
#         url: "https://thewhip.com"
      #- label: "Twitter"
       # icon: "fab fa-fw fa-twitter-square"
        #url: "https://twitter.com/extravagantman"

github: 
  is_project_page: false
